version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install poetry

    post_install:
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      # VIRTUAL_ENV needs to be set manually for now, see #11150
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH
      - pip install sphinx-rtd-theme
      - pip install myst-parser
      - pip install sphinx-mdinclude
      - pip install sphinx-mathjax
      #- source $READTHEDOCS_VIRTUALENV_PATH/bin/activate
      #- poetry install --only docs

sphinx:
  configuration: docs/source/conf.py

#python:
#  install:
#    - method: poetry
#      groups:
#        - docs